[project]
name = "ease-hs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastlite>=0.1.3",
    "monsterui>=1.0.11",
    "python-fasthtml>=0.12.5",
]
